version: 2.1


orbs:
  android: circleci/android@0.2.0
#  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - when:
          condition:
            equal: [develop]
          steps:
            - run:
                name: "build project"
                command:
                  echo "hello world"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
#              ./gradlew build