version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

# version: 2.1
# orbs:
#   android: circleci/android@2.1.2
# executors:
#   my-custom-executor:
#     docker:
#       - image: cimg/base:stable
#         auth:
#           # ensure you have first added these secrets
#           # visit app.circleci.com/settings/project/github/ashishbittoyadav/daggerHilt/environment-variables
#           username: $DOCKER_HUB_USER
#           password: $DOCKER_HUB_PASSWORD
# jobs:
#   my-job-name:

#     executor: my-custom-executor
#     steps:
#       - checkout
#       - run: |
#           # echo Hello, World!

# workflows:
#   my-custom-workflow:
#     jobs:
#       - my-job-name
# version: 2.1
# orbs:
#   android: circleci/android@0.2.0
# #  aws-cli: circleci/aws-cli@3.1.1
# jobs:
#   build:
#     executor: android/android
#     filters:
#       branches:
#         only:
#           -develop
#     steps:
#       - checkout
#       - run:
#           name: "build project"
#           command:
#             ./gradlew build